server:
  port: 8080

spring:
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: gson
  main:
    banner-mode: "off"

logging:
  level:
    root: WARN
    com.microfocus: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

app:
  name: Email Eight Ball
  version: 1.0
  email: dev@localhost.com
  operation: test
