server:
  port: 8080

spring:
  profiles:
    active: prod
  main:
    banner-mode: "off"

logging:
  level:
    root: WARN
    com.microfocus: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

app:
  name: Spring Eight Ball
  version: 1.0

